#!/bin/bash
cat docs.css codemirror.css ambiance.css dialog.css console.css soundbar.css layout.css show-hint.css buttons.css hintclasses.css >> combined.css
java -jar ~/progs/yuicompressor-2.4.8.jar combined.css > combined2.css
mv combined2.css combined.css